import { useState } from "react";import axios from "axios";import { API } from "../App";import { Button } from "../components/ui/button";import { Input } from "../components/ui/input";import { Label } from "../components/ui/label";import { Card } from "../components/ui/card";import { toast } from "sonner";import { User, Mail, Lock, Phone, UserCircle } from "lucide-react";
export default function AuthPage({ setUser }) {  const [isLogin, setIsLogin] = useState(true);
  const [formData, setFormData] = useState({    username: "",    email: "",    phone: "",    password: "",    bio: "",    identifier: "",  });
  const [loading, setLoading] = useState(false);
  const handleSubmit = async (e) => {    e.preventDefault();    setLoading(true);
    try {      const endpoint = isLogin ? "/auth/login" : "/auth/register";      const payload = isLogin        ? { identifier: formData.identifier, password: formData.password }        : formData;
      const response = await axios.post(`${API}${endpoint}`, payload);      localStorage.setItem("token", response.data.token);      setUser(response.data.user);      toast.success(isLogin ? "Connexion réussie!" : "Inscription réussie!");    } catch (error) {      toast.error(error.response?.data?.detail || "Erreur");    } finally {      setLoading(false);    }  };
  return (    <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4">      <div className="w-full max-w-md">        <Card className="bg-slate-900 p-8 border-slate-800">
          {/* Tabs */}          <div className="flex gap-2 mb-6">            <Button              onClick={() => setIsLogin(true)}              className={`flex-1 ${isLogin ? "bg-cyan-500" : "bg-slate-700"}`}            >              Connexion            </Button>
            <Button              onClick={() => setIsLogin(false)}              className={`flex-1 ${!isLogin ? "bg-cyan-500" : "bg-slate-700"}`}            >              Inscription            </Button>          </div>
          <form onSubmit={handleSubmit} className="space-y-5">            {/* LOGIN MODE */}            {isLogin && (              <>                <Label className="text-slate-300">Email / Username / Téléphone</Label>                <Input                  placeholder="ex: tonmail@gmail.com"                  value={formData.identifier}                  onChange={(e) =>                    setFormData({ ...formData, identifier: e.target.value })                  }                  className="bg-slate-800 border-slate-700 text-white"                />              </>            )}
            {/* REGISTER MODE */}            {!isLogin && (              <>                <div>                  <Label className="text-slate-300">                    <User className="inline w-4 h-4 mr-2" /> Nom d'utilisateur                  </Label>                  <Input                    value={formData.username}                    onChange={(e) =>                      setFormData({ ...formData, username: e.target.value })                    }                    className="bg-slate-800 text-white"                    placeholder="@username"                    required                  />                </div>
                <div>                  <Label className="text-slate-300">                    <Mail className="inline w-4 h-4 mr-2" /> Email                  </Label>                  <Input                    value={formData.email}                    onChange={(e) =>                      setFormData({ ...formData, email: e.target.value })                    }                    className="bg-slate-800 text-white"                    placeholder="email@example.com"                    type="email"                    required                  />                </div>
                <div>                  <Label className="text-slate-300">                    <Phone className="inline w-4 h-4 mr-2" /> Téléphone (optionnel)                  </Label>                  <Input                    value={formData.phone}                    onChange={(e) =>                      setFormData({ ...formData, phone: e.target.value })                    }                    className="bg-slate-800 text-white"                    placeholder="06xxxxxxxx"                  />                </div>
                <div>                  <Label className="text-slate-300">                    <UserCircle className="inline w-4 h-4 mr-2" /> Bio (optionnel)                  </Label>                  <Input                    value={formData.bio}                    onChange={(e) =>                      setFormData({ ...formData, bio: e.target.value })                    }                    className="bg-slate-800 text-white"                    placeholder="Parlez de vous..."                  />                </div>              </>            )}
            {/* PASSWORD (COMMUN) */}            <div>              <Label className="text-slate-300">                <Lock className="inline w-4 h-4 mr-2" /> Mot de passe              </Label>              <Input                value={formData.password}                onChange={(e) =>                  setFormData({ ...formData, password: e.target.value })                }                className="bg-slate-800 text-white"                placeholder="••••••••"                type="password"                required              />            </div>
            <Button              type="submit"              disabled={loading}              className="w-full bg-cyan-500 text-white py-3"            >              {isLogin ? "Se connecter" : "S'inscrire"}            </Button>          </form>        </Card>      </div>    </div>  );}
